---

- name: Import Docker APT public key.
  apt_key:
    keyserver: "{{ docker_pubkey_server }}"
    id: "{{ docker_pubkey_id }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Install yum-utils if necessary.
  yum:
    name: yum-utils
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install apt-transport-https if necessary.
  apt:
    name: apt-transport-https
    state: present
  when: ansible_os_family == 'Debian'

- name: Add the YUM Docker repository.
  yum_repository:
    name: docker
    description: Docker Repository
    baseurl: "{{ docker_yum_repo }}"
    gpgkey: "{{ docker_yum_gpgkey }}"
    gpgcheck: yes
  when: ansible_os_family == 'RedHat'

- name: Add the APT Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present
    filename: 'docker'
  when: ansible_os_family == 'Debian'

- name: Install Docker dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_dependencies }}"

- name: Install the Docker Engine.
  package:
    name: docker-engine
    state: present

- name: Enable the Docker daemon as a service and start it.
  service:
    name: docker
    state: started
    enabled: yes
